### ISSUE TITLE
Doesn't work for macOS?

### ISSUE THREAD

**Issue by obitodarky** [Lyutria/aseprite-sunken-theme#1]
I applied it on my macOS Catalina 10.15 and it shows as applied but doesn't seem to work?

![Screenshot 2020-07-29 at 12 00 50 AM](https://user-images.githubusercontent.com/21317964/88706517-9236ff00-d12e-11ea-9784-87f044216466.png)

**Comment by cgxeiji** [comment]
Did you activate it from `Preferences`>`Theme`?

**Comment by obitodarky** [comment]
@cgxeiji I tried to apply it from `Preferences>Theme` as well as `Preferences>Extensions`, under `Extensions` it seems it's already applied because I have the option to `Disable` it, but can't see any changes in the interface

**Comment by obitodarky** [comment]
Looks like I made a mistake. I just tried it with `Preferences > Theme > Select` instead of `Preferences > Theme > Apply` and it worked. 

Wonder what `Apply` is for then? Anyway, closing this issue, thanks :)
