### ISSUE TITLE
Please support the new tilemap icons <3

### ISSUE THREAD

**Issue by oronbz** [Lyutria/aseprite-sunken-theme#2]
It seems that the layer icon is missing, and the other icons are black instead of bright.

I love your theme so much more then the new default aseprite dark theme <3

**Comment by oronbz** [comment]
Ooohh I saw you updated it, but the layer icon is still missing:

Your theme:
![Screen Shot 2022-01-29 at 20 51 59](https://user-images.githubusercontent.com/1288090/151673750-5225d70b-1d27-40cd-9f5b-17b8d1fd0a38.png)

Official:
![Screen Shot 2022-01-29 at 20 51 31](https://user-images.githubusercontent.com/1288090/151673757-42d2ab6e-73bf-44b5-b32e-eb5e85a34031.png)

**Comment by oronbz** [comment]
Fixed here: https://github.com/Lyutria/aseprite-studio-theme/pull/3

**Comment by Lyutria** [comment]
Much appreciated, I didn't realize it was missing. Merged and published a new release.
